name = "anc-expo-management"
compatibility_date = "2026-07-25"

[assets]
directory = "./dist" # أو المجلد الخاص بالـ build لديك
not_found_handling = "single-page-application" # تم تصحيح الكلمة هنا
html_handling = "auto-trailing-slash"         # أو خذ القيمة الفتراضية بإزالته تماماً
